### ISSUE TITLE
Unable to cast object of type 'System.Linq.Expressions.FieldExpression' to type 'System.Linq.Expressions.ConstantExpression'.

### ISSUE THREAD

**Issue by Felk** [adrianiftode/Moq.ILogger#3]
Moq.ILogger seems to be unable to verify with anything that isn't a constant expression. I am using version 1.1.3 and was able to reproduce the error with a simple testcase:

```C#
[Test]
public void ExpressionCastTest()
{
    var loggerMock = new Mock<ILogger<object>>();

    loggerMock.Object.LogInformation("test123");

    // works:
    loggerMock.VerifyLog(logger => logger.LogInformation(It.IsRegex(@"test\d+")));
    // fails:
    string expectedRegex = @"test\d+";
    loggerMock.VerifyLog(logger => logger.LogInformation(It.IsRegex(expectedRegex)));
}
```

with this stacktrace:
```
Moq.VerifyLogUnexpectedException : Moq.ILogger found an unexpected exception.

Please open an issue at https://github.com/adrianiftode/Moq.ILogger/issues/new, provide the exception details and a sample code if possible.
Bellow will follow the unexpected exception details.

  ----> System.InvalidCastException : Unable to cast object of type 'System.Linq.Expressions.FieldExpression' to type 'System.Linq.Expressions.ConstantExpression'.
   at Moq.VerifyLogExtensions.Verify[T](Mock`1 loggerMock, Expression`1 expression, Nullable`1 times, Func`1 timesFunc, String failMessage)
   at Moq.VerifyLogExtensions.VerifyLog[T](Mock`1 loggerMock, Expression`1 expression)
   at Tests.SomeTest.ExpressionCastTest() in D:\Tests\SomeTests.cs:line 76
--InvalidCastException
   at Moq.VerifyLogExtensions.CreateMessageExpression(VerifyLogExpression verifyLogExpression)
   at Moq.VerifyLogExtensions.CreateMoqVerifyExpressionFrom[T](VerifyLogExpression verifyLogExpression)
   at Moq.VerifyLogExtensions.Verify[T](Mock`1 loggerMock, Expression`1 expression, Nullable`1 times, Func`1 timesFunc, String failMessage)
```

**Comment by adrianiftode** [comment]
Thanks for opening this issue. This is now fixed in version 1.1.5
